### ISSUE TITLE
By lazy delegate fields produce an invalid name and fail to compile

### ISSUE THREAD

**Issue by sebaslogen** [LunarWatcher/KClassUnpacker#3]
Example, in a class like this:
```
@AutoUnpack
data class Item( val title: String )  {
    val uniqueId: Int by lazy { 42 }
}
```

The decompiled code has a field like this `private final Lazy uniqueId$delegate;`

And the generated iterator code from @AutoUnpack is:
```
operator fun Item.iterator() = listOf(uniqueId$delegate, title)
```

This iterator function is illegal because the `uniqueId$delegate` name does not match the class field name `uniqueId` and therefore it does not compile

The solution is either to fix the generated name to not include `$delegate` or to ignore variables that contain the `$` character in their name.

**Comment by LunarWatcher** [comment]
Exposing private fields like that isn't a good idea at all actually. I got an idea to handle this, but it'll take a little while to get working. 

I'm going to add an optional, by default false, parameter that makes it ignore private fields. As for ignoring `$`, it's slightly complicated because <code>\`$\`</code> is actually a valid field name:

```kotlin
fun main(args: Array<String>) {
    val `$` = "hello"
    println(`$`)
}
```

I can probably check for the combination, but I'm not entirely sure how it's processed.

**Comment by sebaslogen** [comment]
The lazy field is not private by design, its only purpose is to be used outside of the class and it's a field instead of a method because we want to execute only once the expensive computation of the field's value (the 42 was just to simplify the example).
Regardless of the reason for the public lazy field, the root problem is still the same, the generated variable name in the `Iterator` function is invalid because it doesn't match the name of the field in the class.

**Comment by LunarWatcher** [comment]
It should now work with delegates as well. I've labeled the latest commit, so v1.0.2 should be building now. 

For the sake of transparency and save time on reading through the commit: I check whether the field has a matching getter that's public. If it doesn't, the field is ignored. For delegates, it strips the `$delegate` part before doing so.

**Comment by sebaslogen** [comment]
Awesome, thanks for the fix, I've tested it and it works perfectly.
